# Generated by Django 3.1.4 on 2020-12-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='activity_Event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.activity'),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_Activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.place'),
        ),
        migrations.AlterField(
            model_name='message',
            name='event_Message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_Message_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.user'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event_participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.user'),
        ),
    ]
